server:
  port: 9999

logging:
  level:
    org:
      apache:
        logging: DEBUG
      springframework:
        web: TRACE
        security: TRACE
    resourceserver: TRACE
    httpclient:
      wire: DEBUG


spring:
  security:
    oauth2:
      client:
        registration:
          rs-client:
            provider: as-provider
            client-id: rs-client-id
            client-secret: rs-client-secret
            authorization-grant-type: authorization_code
            scope: openid,profile
        provider:
          as-provider:
            issuer-uri: http://localhost:9000
              
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

management:
  endpoints:
    web:
      exposure:
        include: "*"

auth-server:
  client-registrar:
    client-id: r-c-registrar
    secret: secret


